= Spring Boot Microservices Project

(Eureka Server, Config Server, API Gateway, Kafka, File Storage, JWT, Authentication, Authorization, Redis, Docker)

= About the project

8 services whose name are shown below have been devised within the scope of this project.

* Config Server
* Eureka Server
* API Gateway
* Auth Service
* Job Service
* User Service
* Notification Service
* File Storage

=== Used Dependencies

* Core
** Spring
*** Spring Boot
*** Spring Security
**** Spring Security JWT
**** Authentication
**** Authorization
*** Spring Web
**** FeighClient
*** Spring Data
**** Spring Data JPA
**** PostgreSQL
*** Spring Cloud
**** Spring Cloud Gateway Server
**** Spring Cloud Config Server
**** Spring Cloud Config Client
** Netflix
*** Eureka Server
*** Eureka Client
* Database
** PostgreSQL
* Kafka
* Redis
* Docker
* Validation
* File storage
* Modelmapper
* Openapi UI
* Lombok
* Log4j2

=== Explore Rest APIs

|===
|Method |Url |Description |Valid Request Body |Valid Request Params

|POST |/v1/auth/register |Register for User |#register[Info] |
|POST |/v1/auth/login |Login for User and Admin |#login[Info] |
|GET |/v1/user/getAll |Get all user | |
|GET |/v1/user/getUserById/{id} |Get user by id | |#getUserById[Info]
|GET |/v1/user/getUserByEmail/{email} |Get user by email | |#getUserByEmail[Info]
|PUT |/v1/user/update |Update user |#updateUser[Info] |
|DELETE |/v1/user/deleteUserById/{id} |Delete user by id | |#deleteUserById[Info]
|POST |/v1/job-service/category/create |Category create |#categoryCreate[Info] |
|GET |/v1/job-service/category/getAll |Get all categories | |
|GET |/v1/job-service/category/getCategoryById/{id} |Get category by id | |#getCategoryById[Info]
|PUT |/v1/job-service/category/update |Update category |#updateCategory[Info] |
|DELETE |/v1/job-service/category/deleteCategoryById/{id} |Delete category | |#deleteCategoryById[Info]
|POST |/v1/job-service/job/create |Job create |#jobCreate[Info] |
|POST |/v1/job-service/job/getJobsThatFitYourNeeds |Get jobs that fit your needs |#getJobsThatFitYourNeeds[Info] |
|GET |/v1/job-service/job/getAll |Get all jobs | |
|GET |/v1/job-service/job/getJobById/{id} |Get job by id | |#getJobById[Info]
|PUT |/v1/job-service/job/update |Update job |#updateJob[Info] |
|DELETE |/v1/job-service/job/deleteJobById/{id} |Delete job | |#deleteJobById[Info]
|POST |/v1/job-service/advert/create |Adver create |#advertCreate[Info] |
|GET |/v1/job-service/advert/getAll |Get all adverts | |
|GET |/v1/job-service/advert/getAdvertById/{id} |Get advert by id | |#getAdvertById[Info]
|GET |/v1/job-service/advert/getAdvertsByUserId/{id} |Get advert by user id | |#getAdvertsByUserId[Info]
|PUT |/v1/job-service/advert/update |Update advert |#updateAdvert[Info] |
|DELETE |/v1/job-service/advert/deleteAdvertById/{id} |Delete advert | |#deleteAdvertById[Info]
|POST |/v1/job-service/offer/makeAnOffer |Make an offer |#makeAnOffer[Info] |
|GET |/v1/job-service/offer/getOfferById/{id} |Get offer by id | |#getOfferById[Info]
|GET |/v1/job-service/offer/getOfferByUserId/{id} |Get offer by user id | |#getOfferByUserId[Info]
|GET |/v1/job-service/offer/getOfferByAdvertId/{id} |Get offer by advert id | |#getOfferByAdvertId[Info]
|PUT |/v1/job-service/offer/update |Update offer |#updateOffer[Info] |
|DELETE |/v1/job-service/offer/deleteOfferById/{id} |Delete offer | |#deleteOfferById[Info]
|GET |/v1/notification/getAllByUserId/{userId}} |Get all notification by user id | |#getAllNotificationByUserId[Info]
|GET |/v1/file-storage/download/{id} |Download image to file storage | |#downloadImage[Info]
|===

== Valid Request Body

===== <a id="register"> Register for User

----
    http://localhost:8080/v1/auth/register
    
        {
          "username": "string",
          "password": "string",
          "email": "string"
        }
----

===== <a id="login"> Login for User and Admin

----
      http://localhost:8080/v1/auth/login
    
       {
         "username": "string",
         "password": "string"
       }
----

===== <a id="updateUser"> Update User

----
    http://localhost:8080/v1/user/update
    
    form-data:
        {
          "request": {
            "id": "string",
            "username": "string",
            "password": "string",
            "userDetails": {
              "firstName": "string",
              "lastName": "string",
              "phoneNumber": "string",
              "country": "string",
              "city": "string",
              "address": "string",
              "postalCode": "string",
              "aboutMe": "string",
              "profilePicture": "string"
            }
           },
         "file": "string"
        }
    
    Bearer Token : Authorized User or Admin
----

===== <a id="categoryCreate"> Create Category

----
    http://localhost:8080/v1/job-service/category/create
    
    form data:
    {
      "request": {
        "name": "string",
        "description": "string"
      },
      "file": "string"
    }
    
    Bearer Token : Admin Token
----

===== <a id="updateCategory"> Update Category

----
    http://localhost:8080/v1/job-service/category/updateCategory
    
    form data:
    {
      "request": {
        "id": "string",
        "name": "string",
        "description": "string"
      },
      "file": "string"
    }
    
    Bearer Token : Admin Token
----

===== <a id="jobCreate"> Create Job

----
    http://localhost:8080/v1/job-service/job/create
    
    form data:
       {
      "request": {
        "name": "string",
        "description": "string",
        "categoryId": "string",
        "keys": [
          "string"
        ]
      },
      "file": "string"
    }
    
    Bearer Token : Admin Token
----

===== <a id="updateJob"> Update Job

----
    http://localhost:8080/v1/job-service/job/updateJob
    
    form data:
     {
      "request": {
        "id": "string",
        "name": "string",
        "description": "string",
        "categoryId": "string",
        "keys": [
          "string"
        ]
      },
      "file": "string"
    }
        
    Bearer Token : Admin Token
----

===== <a id="advertCreate"> Create Advert

----
    http://localhost:8080/v1/job-service/advert/create
    
    form data:
     {
      "request": {
        "name": "string",
        "description": "string",
        "deliveryTime": 0,
        "price": 0,
        "advertiser": "EMPLOYEE",
        "userId": "string",
        "jobId": "string"
      },
      "file": "string"
    }
    
    Bearer Token : User Token
----

===== <a id="updateAdvert"> Update Advert

----
    http://localhost:8080/v1/job-service/advert/update
    
    form data:
    {
      "request": {
        "id": "string",
        "name": "string",
        "description": "string",
        "deliveryTime": 0,
        "price": 0,
        "status": "OPEN"
      },
      "file": "string"
    }
        
    Bearer Token : Authorized User or Admin
----

===== <a id="makeAnOffer"> Make An Offer

----
    http://localhost:8080/v1/job-service/offer/makeAnOffer
    
    {
      "userId": "string",
      "advertId": "string",
      "offeredPrice": 0
    }
    
    Bearer Token : User Token
----

===== <a id="updateOffer"> Update Offer

----
    http://localhost:8080/v1/job-service/offer/update
    
    {
      "id": "string",
      "offeredPrice": 0,
      "status": "OPEN"
    }
        
    Bearer Token : Authorized User or Admin
----

== Valid Request Params

===== <a id="getUserById"> Get User By Id

----
    http://localhost:8080/v1/user/getUserById/{id}
    
    Bearer Token : User Token
----

===== <a id="getUserByEmail"> Get User By Email

----
    http://localhost:8080/v1/user/getUserByEmail/{email}
    
    Bearer Token : User Token
----

===== <a id="deleteUserById">Delete User By Id

----
    http://localhost:8080/v1/user/deleteUserById/{id}
    
    Bearer Token : Authorized User or Admin
----

===== <a id="getCategoryById"> Get Category By Id

----
    http://localhost:8080/v1/job-service/category/getCategoryById/{id}
    
    Bearer Token : User Token
----

===== <a id="deleteCategoryById">Delete Category By Id

----
    http://localhost:8080/v1/job-service/category/deleteCategoryById/{id}
    
    Bearer Token : Admin Token
----

===== <a id="getJobById"> Get Job By Id

----
    http://localhost:8080/v1/job-service/job/getJobById/{id}
    
    Bearer Token : User Token
----

===== <a id="getJobsThatFitYourNeeds"> Get Jobs That Fit Your Needs

----
    http://localhost:8080/v1/job-service/job/getJobsThatFitYourNeeds/{needs}
   
    Bearer Token : User Token
----

===== <a id="deleteJobById">Delete Job By Id

----
    http://localhost:8080/v1/job-service/job/deleteJobById/{id}
    
    Bearer Token : Admin Token
----

===== <a id="getAdvertById"> Get Advert By Id

----
    http://localhost:8080/v1/job-service/advert/getAdvertById/{id}
    
    Bearer Token : Authorized User or Admin
----

===== <a id="getAdvertsByUserId"> Get Advert By User Id

----
    http://localhost:8080/v1/job-service/advert/getAdvertByUserId/{id}
    
    Bearer Token : User Token
----

===== <a id="deleteAdvertById">Delete Advert By Id

----
    http://localhost:8080/v1/job-service/job/deleteAdvertById/{id}
    
    Bearer Token : Authorized User or Admin
----

===== <a id="getOfferById"> Get Offer By Id

----
    http://localhost:8080/v1/job-service/offer/getOfferById/{id}
    
    Bearer Token : User Token
----

===== <a id="getOfferByUserId"> Get Offer By User Id

----
    http://localhost:8080/v1/job-service/offer/getOfferByUserId/{id}
    
    Bearer Token : User Token
----

===== <a id="getOfferByAdvertId"> Get Offer By Advert Id

----
    http://localhost:8080/v1/job-service/offer/getOfferByAdvertId/{id}
    
    Bearer Token : User Token
----

===== <a id="deleteOfferById">Delete Offer By Id

----
    http://localhost:8080/v1/job-service/offer/deleteOfferById/{id}
    
    Bearer Token : Authorized User or Admin
----

===== <a id="getAllNotificationByUserId">Get All Notification By User Id

----
    http://localhost:8080/v1/notification/getAllByUserId/{id}
    
    Bearer Token : Authorized User or Admin
----

===== <a id="downloadImage">Download Image to File Storage

----
    http://localhost:8080/v1/file-storage/download/{id}
    
    Bearer Token : User Token
----

=== 🔨 Run the App

<b>1 )</b> Clone project `git clone https://github.com/mkris8/spring-boot-microservices.git`

<b>2 )</b> Go to the project's home directory : `cd spring-boot-microservices`

<b>3 )</b> Run docker compose <b>`docker compose up`</b></b>

<b>4 )</b> Run <b>Eureka Server</b>

<b>5 )</b> Run <b>Gateway</b>

<b>6 )</b> Run <b>Config Server</b>

<b>7 )</b> Run other services (<b>auth-service</b>, <b>user-service</b>, <b>job-service</b>, <b>notification-service</b> and lastly <b>
file-storage</b>)

<b>8 )</b> For swagger ui localhost:8080/v1/{service-name}/swagger-ui/index.html</b>

=== Screenshots